server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faculty_db
    username: postgres
    password: passwors
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: antoci.slavic2001@gmail.com
    password: pasword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

